
#define ERR_NONICKNAMEGIVEN		"431\n"
#define ERR_ERRONEUSNICKNAME	"432\n"
#define ERR_NICKNAMEINUSE		"433\n"
// #define ERR_NICKCOLLISION		"436\n"
#define ERR_NOLOGIN				"444\n"
#define ERR_NEEDMOREPARAMS		"461\n"
#define ERR_PASSWDMISMATCH		"464\n"